### ISSUE TITLE
Use Travis to run tests

### ISSUE THREAD

**Issue by jccaicedo** [broadinstitute/DeepProfiler#12]
https://github.com/travis-ci/travis-ci

**Comment by jccaicedo** [comment]
Let's configure Travis before moving forward with fixing more issues. Travis can help us enforcing style and making sure we cover enough functionality.

**Comment by jccaicedo** [comment]
State of tests 2018-06-27:
43 total tests.
40 passed.
3 failed.

Great job @santient and @massachusett !

**Comment by santient** [comment]
Done: 173531e90ee051353b4b959a240604caa291d486
