### ISSUE TITLE
fix tests

### ISSUE THREAD

**Issue by massachusett** [broadinstitute/DeepProfiler#173]

**Comment by jccaicedo** [comment]
Currently, the tests work on the local development environment, but fail in Travis. Seems to be related to the tensorflow version.

**Comment by jccaicedo** [comment]
Currently, Travis works well with Tensorflow 1.12.2. The latest version fails in Travis infrastructure, even though it works in our local environment. Will close this issue for now, but let's keep an eye on TF versions.
